#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-PyYAML
Version  : 3.13
Release  : 51
URL      : https://github.com/yaml/pyyaml/archive/3.13.tar.gz
Source0  : https://github.com/yaml/pyyaml/archive/3.13.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: deprecated-PyYAML-license = %{version}-%{release}
Requires: deprecated-PyYAML-python = %{version}-%{release}
BuildRequires : Cython
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3
BuildRequires : deprecated-Cython-legacypython
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : yaml-dev
Patch1: 0001-CVE-2017-18342-1.patch
Patch2: 0002-CVE-2017-18342-2.patch

%description
PyYAML - The next generation YAML parser and emitter for Python.
To install, type 'python setup.py install'.

%package legacypython
Summary: legacypython components for the deprecated-PyYAML package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-PyYAML package.


%package license
Summary: license components for the deprecated-PyYAML package.
Group: Default

%description license
license components for the deprecated-PyYAML package.


%package python
Summary: python components for the deprecated-PyYAML package.
Group: Default
Provides: deprecated-pyyaml-python

%description python
python components for the deprecated-PyYAML package.


%prep
%setup -q -n pyyaml-3.13
%patch1 -p1
%patch2 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554349395
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python setup.py test || :
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-PyYAML
cp LICENSE %{buildroot}/usr/share/package-licenses/deprecated-PyYAML/LICENSE
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-PyYAML/LICENSE

%files python
%defattr(-,root,root,-)
